(() => {
  const support={
    structures:{start:[['Find the job','Separate the jobs: store genetic information; control exchange; make proteins; carry out aerobic respiration. Match one job at a time.'],['Build your sentence','“The ___ carries out ___. This helps the cell ___.” Use the coloured structure key, then close it.']],understand:[['Separate membrane and wall','A cell membrane regulates exchange. A cellulose cell wall supports a plant cell. Point to the boundary that performs each job.'],['Try again without the key','Close the support. Name the structure for protein synthesis, then the structure for aerobic respiration. Explain one difference.']],hot:[['Connect two structures','A cell makes and releases many proteins. Explain why both ribosomes and mitochondria are useful.'],['Challenge the claim','“Bacteria have no mitochondria, so they cannot release energy.” Explain why the first part does not prove the second.']]},
    groups:{start:[['Sort the evidence','Underline evidence about a nucleus, cell wall material and the number of cells in the organism. These are different clues.'],['Build a decision','“I classify it as ___ because ___. The clue ___ alone would not be enough.” Name the decisive evidence.']],understand:[['One cell is not one group','Yeast and bacteria can both be single-celled. Compare their nuclei and cell walls before making your decision.'],['Remove the support','Close this panel. Reclassify one case and explain why a different group does not fit its evidence.']],hot:[['What is missing?','A specimen has a nucleus and no chloroplasts. Explain why this is not enough to identify its group. What further evidence would help?'],['Test a rule','“Every cell with chloroplasts belongs to a plant.” Use a counterexample, then write a more careful rule.']]},
    fungi:{start:[['Unpack the new words','A hypha is one thread. A mycelium is a network of hyphae. Chitin is a material in fungal cell walls.'],['Follow the food','Put these in order: release enzymes; absorb soluble products; digest material outside the fungus.']],understand:[['Keep the location clear','In saprotrophic nutrition, digestion happens outside the organism. Absorption brings soluble products into it. These are different steps.'],['Say it independently','Close this panel. Explain how a fungus obtains nutrients from dead material using “enzymes” and “absorb”.']],hot:[['Use the exception','Yeast is a single-celled fungus. Which fungal features still help identify it even though it has no network of hyphae?'],['Explain the mechanism','Why is absorbing soluble products different from taking a whole piece of food into the organism?']]},
    differentiation:{start:[['Feature → function','First name the specialised structure. Next name its job. Finally explain how that job helps the cell.'],['Use a sentence opening','“A palisade cell has many ___. These absorb ___ for ___.” Complete it, then explain without the opening.']],understand:[['Two different changes','Division increases cell number. Differentiation develops specialised structures and functions. Which change does the question describe?'],['Fade the scaffold','Close the panel. Explain how a palisade cell is suited to photosynthesis, linking its feature to its function.']],hot:[['Compare specialisms','A nerve cell has a long axon; a palisade cell has many chloroplasts. Explain why these structures suit different jobs.'],['Think about genes','Most body cells contain the same genes. How could different genes being active help explain different structures and functions?']]},
    stem:{start:[['Two abilities','Keep two headings: “stem cells remain” and “specialised cells form”. Add the name of the process under each.'],['Compare the range','Use “almost all body-cell types” and “a more restricted range”. Compare the sources using one sentence.']],understand:[['Restricted does not mean one','Blood-forming adult stem cells can form several blood-cell types. Explain why “adult stem cells make only one cell type” is too narrow.'],['Remove the branch labels','Close this panel. Draw a stem cell with two branches. Label each ability and describe what it produces.']],hot:[['Is the evidence enough?','Two unidentified stem-cell samples both make blood cells. Is that enough to identify their sources? Explain what the observation does and does not show.'],['Separate number and function','A cell population doubles but remains unspecialised. Which stem-cell ability does that support? What has not yet been shown?']]},
    repair:{start:[['Build a benefit chain','Replacement cells → the correct specialised job → improved tissue function. Use the chain to explain a possible benefit.'],['Build a risk chain','Uncontrolled division → a mass of cells → a possible tumour. A biological risk needs a mechanism and a consequence.']],understand:[['Separate two kinds of concern','A biological risk describes what could happen in a body. An ethical concern asks what should be permitted. Explain the difference.'],['Close and explain','Without these prompts, give one possible benefit and one biological risk. Include the result of each.']],hot:[['Evaluate the proposal','Would rapid cell division alone show that a treatment can repair tissue? Explain two further things that must be established.'],['Weigh evidence','A trial reports more cells but no improvement in tissue function. Explain why this does not yet establish a successful treatment.']]},
    evaluate:{start:[['Plan both sources','Make four boxes: embryonic benefits, embryonic limitations, own bone-marrow benefits, own bone-marrow limitations. Add short notes before writing.'],['Make a linked point','“Source ___ could help because ___. Compared with ___, this matters because ___.” Connect the biology to the tissue in the question.']],understand:[['Move beyond a list','Choose one advantage and one disadvantage. Explain what each would mean for the proposed treatment. Do not count repeated wording as a new idea.'],['Remove the scaffold','Close this panel. Write your response independently and finish with a judgement supported by the evidence.']],hot:[['Separate laboratory and patient evidence','Cells contract in a dish. What further evidence would show they can work safely in a patient’s heart?'],['Make the judgement conditional','Explain how evidence of poor cell survival or uncontrolled division could change your preferred source.']]}

  };
  const p=(id,family,type,title,topic,extra={})=>({id,family,type,title,topic,support:support[topic],...extra});
  window.LESSON={
    number:1,unit:'Cells',unitLesson:4,title:'Cells and stem cells',question:'What do a cell’s features tell us?',path:['Review cell evidence','Explain why cells specialise','Evaluate medical uses'],
    outcomes:[['Explain why differentiation is important in developing specialised cells.','2.5B · Biology only'],['Compare advantages and disadvantages of using stem cells in medicine.','2.6B · Biology only'],['Classify organisms using cell evidence and recall structure–function links.','1.2, 1.3, 2.2–2.4 · selected review']],
    structures:[
      {id:'nucleus',name:'Nucleus',color:'#a99ac5',text:'Contains most of a typical eukaryotic cell’s genetic information.'},
      {id:'membrane',name:'Cell membrane',color:'#8db4bd',text:'Regulates the movement of substances into and out of the cell.'},
      {id:'ribosomes',name:'Ribosomes',color:'#b45c70',text:'Make proteins. This process is called protein synthesis.'},
      {id:'mitochondria',name:'Mitochondria',color:'#d99355',text:'Sites of aerobic respiration, which releases energy for cell activities.'}
    ],
    vocabulary:[['Eukaryotic','Cells typically have a membrane-bound nucleus. Plants, animals, fungi and protoctists are eukaryotic.'],['Prokaryotic','Cells have no membrane-bound nucleus. In bacteria, the circular chromosome lies in the cytoplasm.'],['Chitin / cellulose','Chitin is found in fungal cell walls. Cellulose is found in plant cell walls. A membrane is a different structure.'],['Hypha / mycelium','A hypha is a fungal thread. A mycelium is a network of hyphae.'],['Saprotrophic nutrition','Enzymes digest dead material outside the organism. Soluble digestion products are then absorbed.'],['Differentiation','Unspecialised cells develop specialised structures and functions. This produces cell types that work together in tissues and organs.'],['Self-renewal','Division that maintains a population of undifferentiated stem cells.'],['Biological risk','A possible harmful effect in a living organism, such as uncontrolled cell division producing a tumour.'],['Immune rejection','The immune system may recognise donor cells as foreign and attack them. Using a patient’s own cells avoids donor mismatch, but does not remove all treatment risks.'],['Ethical concern','A judgement about what should be permitted. Some people object to embryo destruction; others weigh this against possible medical benefits.'],['Evaluate','Weigh relevant strengths and weaknesses, apply them to the situation, and reach a judgement supported by evidence.']],
    resourcePages:[{heading:'Exam-style practice',text:'Short explanations, a guided six-mark evaluation and an independent medical application.',href:'04%20Resources/Exam-style%20questions.html',linkLabel:'Open the question sheet'},{heading:'Ready to learn',items:['Book and pen','Ruler for diagrams','Mini-whiteboard, if available'],text:'Record your thinking in your book. Use the reference only when directed.'},{heading:'Classification task',text:'Cases A–F, independent application and the exit check.',href:'04%20Resources/Classification%20task.html',linkLabel:'Open the task sheet'},{heading:'Cell features reference',text:'Compare groups and revisit key structures and functions.',href:'04%20Resources/Cell%20features%20reference.html',linkLabel:'Open the reference'},{heading:'Read the teaching input',text:'Revisit the explanations after the lesson.',href:'04%20Resources/Lesson%201%20input.html',linkLabel:'Open the reading'}],
    modelPages:[{heading:'Explore a cell',text:'Match each structure to its function.',action:{id:'structures',label:'Open the cell model'}},{heading:'Model a classification',text:'Follow the evidence one step at a time.',action:{id:'classify-model',label:'Open the worked example'}},{heading:'Stem-cell abilities',text:'Distinguish keeping stem cells from producing specialised cells.',action:{id:'stem-abilities',label:'Open the branching model'}}],
    checkPages:[{heading:'Explain why differentiation matters',text:'Apply 2.5B in a two-mark explanation.',action:{id:'differentiation-exam',label:'Open the differentiation question'}},{heading:'Build an evaluation',text:'Plan and develop the guided six-mark response.',action:{id:'guided-evaluation',label:'Open the guided exam question'}},{heading:'Apply to a new tissue',text:'Write an independent six-mark evaluation of the heart-repair proposal.',action:{id:'independent-evaluation',label:'Open the independent exam question'}},{heading:'Recall the structures',text:'Match four functions to their structures.',action:{id:'structure-recheck',label:'Open the short recheck'}},{heading:'Classify with evidence',text:'Use a combination of features to identify one organism.',action:{id:'classification-hinge',label:'Open the hinge question'}},{heading:'Apply independently',text:'Classify three fresh specimens using decisive evidence.',action:{id:'independent-1',label:'Open independent application'}},{heading:'Show what changed',text:'Explain why differentiation matters and why source choice depends on the tissue.',action:{id:'exit',label:'Open the exit check'}}],
    phases:[
      p('title','Title','title','Cells and stem cells','groups'),
      p('outcomes','Learning outcome','outcome','What will you be able to do?','groups',{nav:'Learning outcomes'}),
      p('do-now','Do now','content','Start from memory','structures',{nav:'Do now',lead:'Write four brief answers in your book.',items:['Which structure contains most genetic information in a typical eukaryotic cell?','Which structure regulates movement into and out of a cell?','What do ribosomes do?','What happens in mitochondria?']}),
      p('structures','Input','structures','Four structures, four jobs','structures',{task:'Connect each structure to its job. Say the structure and function together.'}),
      p('structure-recheck','Assess','content','Close the model. Recall the structure.','structures',{nav:'Recall four structures',lead:'Write the name of the structure for each function.',items:['Protein synthesis','Regulating exchange with the surroundings','Aerobic respiration','Containing most genetic information in a typical eukaryotic cell'],task:'Then explain why a cell membrane and a cell wall are different.'}),
      p('bacteria-yeast','Input','content','One cell does not mean one group','groups',{nav:'Bacteria and yeast',diagram:'bacteriaYeast',items:['<strong>Bacteria:</strong> no nucleus; a circular chromosome lies in the cytoplasm.','<strong>Yeast:</strong> a single-celled fungus with a nucleus and a chitin wall.','Both have a membrane, cytoplasm and ribosomes.'],task:'A nucleus is evidence for a eukaryotic cell. Bacteria are prokaryotic.'}),
      p('plants-animals','Input','content','Compare plants and animals','groups',{nav:'Plants and animals',diagram:'plantAnimal',items:['Both are multicellular and eukaryotic.','Plants have <strong>cellulose walls</strong>. Photosynthetic cells have chloroplasts. Plants can store starch.','Animals have <strong>no cell walls or chloroplasts</strong>. They feed on organisms and can store glycogen.'],task:'A plant root cell may have no chloroplasts. It still has a cellulose wall.'}),
      p('protoctists','Input','content','Chloroplasts are not enough','groups',{nav:'Plants and protoctists',diagram:'plantProtoctist',items:['Plants are multicellular.','<strong>Chlorella</strong> is a single-celled protoctist with a nucleus and chloroplasts.','Protoctists vary: some photosynthesise; others, such as Amoeba, do not.'],task:'Use the number of cells in the whole organism as well as its cell structures.'}),
      p('fungi','Input','content','How do fungi get nutrients?','fungi',{nav:'Fungal features',diagram:'fungi',items:['Many fungi grow as <strong>hyphae</strong>: threads forming a <strong>mycelium</strong>. Their walls contain chitin.','In <strong>saprotrophic nutrition</strong>, released enzymes digest dead material outside the organism.','The fungus absorbs the soluble digestion products.'],task:'Yeast is a single-celled fungus. Not all fungi form a mycelium.'}),
      p('classify-model','Input','model','Use the strongest evidence','groups',{nav:'Model a classification',lead:'One cell. A nucleus. A chitin wall. No chloroplasts.',diagram:'bacteriaYeast',steps:['The nucleus supports “eukaryotic”. Being single-celled does not make the specimen a bacterium.','The chitin wall is the decisive clue here. I classify this organism as a fungus.','No chloroplasts alone would not be enough: animal cells and many protoctists also lack them.'],task:'What extra information would you need if you only knew “nucleus, no chloroplasts”?'}),
      p('classification-hinge','Assess','hinge','Which group fits all the evidence?','groups',{nav:'Classification check',lead:'One cell · nucleus · chitin wall · no chloroplasts',options:['Plant','Animal','Fungus','Bacterium'],task:'Choose a group. Explain why “one cell” cannot settle the question.'}),
      p('independent-1','Assess','cases','Classify three fresh specimens [6]','groups',{nav:'Independent: classify',lead:'Work from memory. Give a group and decisive evidence for each specimen.',cases:[['X','Circular chromosome in the cytoplasm. No membrane-bound nucleus.'],['Y','Threads with chitin walls and nuclei.'],['Z','One free-living cell with a nucleus and chloroplasts.']],task:'Two marks per specimen: state the group and give supporting evidence.'}),
      p('differentiation','Input','content','Differentiation changes the job','differentiation',{nav:'Define differentiation',diagram:'palisade',items:['An unspecialised cell develops structures suited to a particular function. This is <strong>differentiation</strong>.','Different genes become active, so cells can make different proteins.','Palisade cells contain many chloroplasts, which absorb light for photosynthesis.'],task:'Mitosis increases cell number. Differentiation develops specialised cell types.'}),
      p('importance','Input','content','Why is differentiation important?','differentiation',{nav:'2.5B · why differentiation matters',items:['A multicellular organism needs different jobs done: for example, carrying impulses and contracting.','Differentiation produces cells with structures suited to these different jobs.','Specialised cells work together in tissues and organs, allowing the organism to function.'],task:'More identical, unspecialised cells would not provide all these different functions.'}),
      p('specialised-examples','Input','cases','Different structures support different jobs','differentiation',{nav:'Specialised cells in tissues',cases:[['P','Palisade cells: many chloroplasts absorb light for photosynthesis in a leaf.'],['N','Nerve cells: a long axon carries impulses over a distance.'],['M','Heart-muscle cells: specialised contractile proteins let them contract, helping the heart pump blood.']],task:'Most nucleated body cells contain the same genes. Different genes being active helps explain their different jobs.'}),
      p('palisade-practice','Thinking','content','Link the feature to the function','differentiation',{nav:'Explain a palisade cell',diagram:'palisade',text:'An unspecialised plant cell develops into a palisade cell.',items:['Name the process.','Explain how having many chloroplasts helps the cell carry out its job.'],task:'Write a complete explanation: feature → what it does → why that helps.'}),
      p('independent-2','Assess','content','Apply the plant-cell evidence [4]','differentiation',{nav:'Independent: plant cells',items:['<strong>[2]</strong> An onion-bulb cell has a cellulose wall but no chloroplasts. Explain why “it cannot be a plant cell” is not justified.','<strong>[2]</strong> An unspecialised plant cell develops into a palisade cell with many chloroplasts. Name the process and explain how this feature supports its function.'],task:'Use short explanations that connect the evidence to your conclusion.'}),
      p('differentiation-exam','Assess','content','Explain why differentiation matters [2]','differentiation',{nav:'Exam-style question · 2.5B',label:'Original exam-style question · 2 marks',text:'Explain why producing more cells by mitosis is not enough to develop a functioning multicellular organism.',task:'Write a linked explanation in your book. Use the idea of specialised cells.',support:{...support.differentiation,start:[['Start with the missing change','Mitosis increases cell number. What must happen for cells to perform different jobs?'],['Connect to the organism','Explain how different cell types work together. Move from the cell to a tissue or organ.']],understand:[['Explain importance, not only meaning','A definition describes differentiation. Add why an organism needs it.'],['Try without the prompt','Close this panel. Explain why having more unspecialised cells would not be enough.']]}}),
      p('stem-abilities','Input','content','A stem cell has two key abilities','stem',{nav:'Stem-cell abilities',diagram:'stem',caption:'A population model of two abilities; it does not prescribe a fixed ratio of daughter cells.',items:['<strong>Self-renewal:</strong> division by mitosis maintains a population of undifferentiated stem cells.','<strong>Differentiation:</strong> stem cells can produce specialised cells.'],task:'Making more unspecialised cells is not the same as making specialised cells.'}),
      p('stem-sources','Input','content','The source affects the range','stem',{nav:'Embryonic and adult sources',diagram:'sources',items:['<strong>Embryonic stem cells</strong> come from early embryos. They can produce almost all body-cell types.','<strong>Adult tissue stem cells</strong> occur in tissues such as bone marrow. They usually produce a more restricted range.','Blood-forming adult stem cells can produce several blood-cell types.'],task:'“Restricted range” does not mean “only one type”.'}),
      p('stem-practice','Assess','content','Recall and compare [4]','stem',{nav:'Short stem-cell practice',label:'Original exam-style questions · 4 marks',items:['State two key abilities of a stem cell. <strong>[2]</strong>','Compare the range of cell types produced by embryonic stem cells and adult blood-forming bone-marrow stem cells. <strong>[2]</strong>'],task:'Answer from memory, then explain the comparison to a partner.'}),
      p('medical-uses','Input','content','Using stem cells in medicine','repair',{nav:'Established use and proposed repair',items:['<strong>Established use:</strong> blood-forming stem-cell transplants can restore blood-cell production in treatment for some blood cancers.','<strong>Proposed repair:</strong> embryonic stem cells could supply other specialised cell types if their development is controlled.','Replacement cells must survive and do the tissue’s job. Making the right cell type in a laboratory does not prove a treatment works.'],task:'For heart repair, replacement muscle cells would need to contract and help the heart pump.'}),
      p('source-tradeoffs','Input','content','Compare the two sources','repair',{nav:'Medical advantages and limitations',items:['<strong>Embryonic:</strong> broad potential offers more possible cell types for repair. Division and differentiation must be controlled.','<strong>Adult blood-forming bone marrow:</strong> useful for producing blood cells, but its restricted range limits other proposed repairs.','Using a patient’s own cells avoids donor mismatch. Donor cells may be recognised as foreign and rejected.'],task:'A good tissue match does not mean every treatment risk has disappeared.'}),
      p('repair-benefit','Input','model','How could replacement cells help?','repair',{nav:'A possible benefit',diagram:'stem',steps:['Stem cells can produce specialised replacement cells. The cell type must match the job the damaged tissue needs.','If replacement cells work correctly in the tissue, they may help restore its function.','More cells alone do not prove repair. The correct cell type and controlled growth are necessary.'],task:'Explain the benefit as a chain: replacement cells → correct job → improved function.'}),
      p('repair-risk','Input','content','Explain risks and ethical concerns','repair',{nav:'2.6B · disadvantages in medicine',items:['<strong>Biological risk:</strong> uncontrolled division, including from undifferentiated cells left in a preparation, may produce a tumour.','<strong>Donor mismatch:</strong> the immune system may attack donor cells. Matching and immune-suppressing medicines may be needed.','<strong>Ethics:</strong> obtaining embryonic cells can destroy an embryo. Some people object because they regard it as potential human life.'],task:'Others weigh embryo use against possible benefits for patients. Explain the concern respectfully.'}),
      p('guided-evaluation','Thinking','content','Evaluate the two sources [6]','evaluate',{nav:'Guided exam-style evaluation',label:'Original exam-style question · 6 marks',text:'A research team proposes replacing damaged nerve cells. It can use embryonic stem cells or a patient’s own blood-forming bone-marrow stem cells.',items:['For this question, the bone-marrow cells can form blood cells but cannot form working nerve cells.','<strong>Evaluate</strong> the two sources for this proposed treatment.'],task:'Plan both sources first. Weigh benefits and limitations, then support a judgement.'}),
      p('evaluation-model','Input','model','Develop a comparative explanation','evaluate',{nav:'Model one part of the answer',diagram:'sources',steps:['Start with a scientific difference: embryonic stem cells have a broader range of possible cell types than the blood-forming bone-marrow cells.','Link it to this case: embryonic cells could provide replacement nerve cells, whereas the stated bone-marrow cells cannot.','Now add your own contrasting point about a risk or ethical concern. Explain its effect, then write a supported judgement.'],task:'Use the model to explain a difference. The full response must weigh the evidence, not just list facts.'}),
      p('independent-evaluation','Assess','content','Evaluate a new repair proposal [6]','evaluate',{nav:'Independent exam-style evaluation',label:'Original exam-style question · 6 marks',lead:'Eight minutes · work independently',text:'Researchers propose repairing damaged heart muscle. In a laboratory study, embryonic stem cells produced contracting heart-muscle cells. The patient’s own blood-forming bone-marrow stem cells produced only blood cells.',task:'Evaluate the two sources for the proposed repair. Include a judgement supported by the evidence. Write independently in your book.'}),
      p('exam-review','Assess','content','Review the reasoning in your answer','evaluate',{nav:'Review and improve',items:['Identify where you compared the two sources in the heart-repair context.','Find a biological limitation and an ethical consideration. Explain their consequences where needed.','Underline your supported judgement. Identify any extra evidence needed before claiming success.'],task:'Use the feedback discussed in class to improve one weak link. This is an answer review, not a fixed formula for marks.'}),
      p('exit','Assess','content','Finish with the two key outcomes','differentiation',{nav:'Exit · 2.5B and 2.6B',items:['Explain why differentiation matters to a multicellular organism.','Give one reason the best stem-cell source depends on the tissue being repaired.'],task:'Use a cause-and-effect explanation, rather than only defining a term.'})
    ]
  };
})();
