(() => {
  const support={
    osmosis:{start:[['Label before explaining','Draw “inside” and “outside”. Write the sucrose concentration on each side. Circle the more dilute solution.'],['Build a sentence','“There is net movement of water from ___ to ___ through the partially permeable membrane.” Add the concentration comparison.']],understand:[['Name the moving substance','In this model, water can cross the membrane and sucrose cannot. Osmosis describes the net movement of water.'],['Close and recheck','Without the sentence opening, explain what happens with 5% sucrose inside and 15% outside. Use water, direction and membrane.']],hot:[['At equal concentration','No net water movement does not mean that water molecules stop. Explain both statements using movement in each direction.'],['Test the model boundary','What would be harder to predict if the membrane also allowed sucrose to move? Identify the assumption that has changed.']]},
    tissue:{start:[['Follow water first','First decide the net direction of water. Then connect water gained or lost to the tissue’s mass.'],['Build the plant-cell chain','Water enters → vacuole expands → contents press against the wall. Use this chain to explain firmness.']],understand:[['Wall and membrane differ','The membrane controls exchange. The cellulose wall supports the cell and resists expansion. Do not describe the wall as the selective barrier.'],['Recheck without the chain','Close this panel. Explain how a more concentrated outside solution can reduce the mass and firmness of potato tissue.']],hot:[['Compare cell types','Why can a plant cell become turgid in water while an animal cell may burst? Link the difference to a structure.'],['Explain an unchanged mass','A cylinder finishes with the same mass. Why does this not prove that no water molecules crossed cell membranes?']]},
    mass:{start:[['Find the change first','Write final mass minus initial mass. Keep the negative sign if the final mass is smaller.'],['Choose the denominator','Divide the change by the initial mass, then multiply by 100. The initial mass is your starting reference.']],understand:[['Interpret the sign','A positive percentage means mass increased. A negative percentage means mass decreased. Link the sign to net water movement.'],['Try it unaided','Close this panel. Set out the calculation for 2.50 g changing to 2.20 g. Include the sign and the % symbol.']],hot:[['Make a fair comparison','Two cylinders each gain 0.20 g, but they started at 1.00 g and 2.00 g. Compare the percentage changes and explain why raw gains are misleading.'],['Challenge the inference','Does a 0% mass change prove the cylinder contains no sucrose? Explain why the evidence cannot establish that.']]},
    method:{start:[['Separate the variables','Change: sucrose concentration. Measure: percentage change in mass after a fixed time. Keep other relevant conditions consistent.'],['Explain one control','Choose one: cylinder dimensions, potato source, time, solution volume or temperature. Explain how changing it could affect the result.']],understand:[['Think about the balance','Liquid on the outside also adds to the balance reading. Explain why blotting should be gentle and consistent before weighing.'],['Fade the list','Close this panel. Name two controls and explain why each matters. Add one reason for repeating measurements.']],hot:[['Evaluate a method','One cylinder stays in a solution for ten minutes and another for forty. Can a mass difference be attributed only to concentration? Explain.'],['Separate precision and validity','Repeated readings are very similar, but every cylinder was weighed with liquid on its surface. Explain what repeats have not corrected.']]}
  };
  const p=(id,family,type,title,topic,extra={})=>({id,family,type,title,topic,support:support[topic],...extra});
  window.LESSON={
    number:2,title:'Assessment and osmosis',question:'Show what you know. Then explain why water moves.',path:['Yellow sheet','Osmosis theory','Prepare for Week 4'],
    outcomes:[['Explain osmosis using water, concentration and a partially permeable membrane.','2.15 · osmosis component'],['Predict and explain changes in plant tissue in different solutions.','2.15'],['Calculate percentage mass change and identify variables for the potato investigation.','2.16 · selected controls; 2.17 · preparation']],
    vocabulary:[['Osmosis','The net movement of water from a more dilute solution to a more concentrated solution through a partially permeable membrane.'],['Partially permeable membrane','A membrane that allows some substances to cross while restricting others. In our model, water crosses but sucrose does not.'],['Net movement','The overall result of movement in both directions. More water moves one way than the other.'],['Dilute / concentrated','A dilute solution has less dissolved solute relative to the water. A concentrated solution has more. Compare the same solute on the same scale.'],['Water potential','Water moves by osmosis from higher to lower water potential. Adding solute lowers water potential; compare solutions at the same pressure.'],['Turgid','A plant cell whose contents press against the cell wall after water enters. The wall resists further expansion.'],['Plasmolysed','A plant cell that has lost enough water for its membrane to pull away from the cell wall.'],['Percentage change in mass','(Final mass − initial mass) ÷ initial mass × 100. A negative value represents mass loss.']],
    resourcePages:[{heading:'Ready for the theory',items:['Book and pen','Ruler for arrows and labels','Calculator for percentage change'],text:'The potato practical takes place in Week 4.'},{heading:'Osmosis practice',text:'Use the three model-cell cases, then prepare your explanation of the potato investigation.',href:'02%20Resources/Osmosis%20practice.html',linkLabel:'Open the task sheet'},{heading:'Revisit the input',text:'Read the osmosis explanation and worked percentage example.',href:'02%20Resources/Osmosis%20input.html',linkLabel:'Open the reading'},{heading:'Yellow sheet',text:'The six-question cell assessment. Complete it before the osmosis teaching.',href:'03%20Yellow%20sheet%20-%20draft.pdf',linkLabel:'Open the assessment PDF'}],
    modelPages:[{heading:'Water and the membrane',text:'Explore different outside concentrations while the inside begins at 5% sucrose.',action:{id:'osmosis-model',label:'Open the concentration model'}},{heading:'Plant cells and water',text:'Connect water movement to turgor and mass.',action:{id:'plant-tissue',label:'Open the tissue model'}},{heading:'Percentage mass change',text:'Follow the worked example one step at a time.',action:{id:'mass-model',label:'Open the calculation model'}}],
    checkPages:[{heading:'Yellow sheet',text:'20 marks. Work independently for 22 minutes.',action:{id:'yellow-sheet',label:'Open the assessment screen'}},{heading:'Predict in three cases',text:'Use concentrations to predict net water movement.',action:{id:'guided-cases',label:'Open the guided cases'}},{heading:'Check the direction',text:'Decide which statement fits the membrane model.',action:{id:'osmosis-hinge',label:'Open the hinge question'}},{heading:'Explain a result',text:'Use water, membrane and concentration in your explanation.',action:{id:'exit',label:'Open the exit check'}}],
    phases:[
      p('title','Title','title','Assessment and osmosis','osmosis'),
      p('yellow-sheet','Assess','exam','Show what you know','osmosis',{nav:'Yellow sheet · 22 minutes',label:'Independent assessment',secure:true}),
      p('collect','Assess','content','Finish the assessment','osmosis',{nav:'Collect the yellow sheets',secure:true,items:['Put your pen down when directed.','Hand in your yellow sheet.','Open your book for the osmosis lesson.'],task:'The next task is a prediction about water and potato tissue.'}),
      p('outcomes','Learning outcome','outcome','What will you be able to explain?','osmosis',{nav:'Osmosis learning outcomes',lead:'This theory prepares you for the Week 4 potato investigation.'}),
      p('predict','Do now','content','What might happen to the potato?','osmosis',{nav:'Predict before the explanation',diagram:'potato',text:'Two identical pieces of living potato tissue go into different solutions.',items:['Predict a change in mass or firmness in each beaker.','Give a reason. You can revise it after the explanation.'],task:'Think alone first. Record your prediction in your book.'}),
      p('osmosis-definition','Input','content','Osmosis is the net movement of water','osmosis',{nav:'What is osmosis?',diagram:'membrane',text:'Water moves by osmosis from a <strong>more dilute solution</strong> to a <strong>more concentrated solution</strong>, through a <strong>partially permeable membrane</strong>.',items:['Water crosses the membrane in both directions.','Osmosis is passive: the cell does not supply energy from respiration for it.'],task:'In this model, water can cross. Sucrose cannot.'}),
      p('osmosis-model','Input','osmosis','Compare the two solutions','osmosis',{nav:'Explore net water movement'}),
      p('net-movement','Input','content','What does “net” mean?','osmosis',{nav:'Both directions; one net change',items:['If more water crosses one way than the other, there is <strong>net movement</strong> in that direction.','At equal water potential, water still crosses both ways, with <strong>no net movement</strong>.','For these solutions at the same pressure, adding sucrose lowers water potential.'],task:'No net movement does not mean that individual water molecules have stopped.'}),
      p('guided-cases','Thinking','cases','Predict. Draw. Explain.','osmosis',{nav:'Three osmosis cases',lead:'Each model cell starts at 5% sucrose inside. Water can cross its membrane; sucrose cannot.',cases:[['A','Outside: 0% sucrose (water)'],['B','Outside: 15% sucrose'],['C','Outside: 5% sucrose']],task:'Draw the net water direction for each case, or write “no net movement”. Explain using both concentrations.'}),
      p('osmosis-hinge','Assess','hinge','Which statement fits this model?','osmosis',{nav:'Osmosis hinge check',lead:'Inside: 5% sucrose. Outside: 15%. Water crosses; sucrose does not.',options:['Net water enters because the inside has less sucrose.','Net water leaves through the partially permeable membrane.','Sucrose enters the cell by osmosis.','The membrane blocks all water movement.'],task:'Choose one. Use the concentrations to justify the direction.'}),
      p('plant-tissue','Input','content','Link water movement to the tissue','tissue',{nav:'Potato mass and firmness',diagram:'potato',items:['In a more dilute solution, net water enters living potato cells. The tissue usually gains mass and becomes firmer.','In a solution more concentrated than the cell sap, net water leaves. The tissue usually loses mass and becomes less firm.'],task:'The cell membrane is the partially permeable barrier. The cellulose wall supports the cell.'}),
      p('turgor','Input','content','Why does firmness change?','tissue',{nav:'Turgor and water loss',diagram:'turgor',items:['Water enters: the vacuole expands. The contents press against the wall: the cell becomes <strong>turgid</strong>.','Water leaves: turgor falls. With enough loss, the membrane pulls away from the wall: <strong>plasmolysis</strong>.'],task:'During plasmolysis, the cell wall does not shrink away with the membrane.'}),
      p('mass-model','Input','model','Calculate percentage mass change','mass',{nav:'Worked mass calculation',diagram:'potato',caption:'Illustrative potato measurements for learning; not results from our practical.',lead:'Initial mass: 2.50 g. Final mass: 2.80 g.',steps:['Find the change: 2.80 − 2.50 = +0.30 g.','Compare with the initial mass: +0.30 ÷ 2.50 = +0.12.','Multiply by 100: +0.12 × 100 = +12%. The tissue gained mass.'],task:'Percentage change = (final − initial) ÷ initial × 100'}),
      p('mass-practice','Assess','content','Now calculate a mass loss','mass',{nav:'Calculate independently',lead:'Illustrative measurements: 2.50 g before, 2.20 g after.',formula:['Percentage change in mass =','(final mass − initial mass) ÷ initial mass × 100'],items:['Set out the calculation. Keep the sign.','Explain what your percentage tells you about the tissue.'],task:'Use your answer to describe the net movement of water.'}),
      p('practical-variables','Input','content','Prepare a useful comparison','method',{nav:'Plan the variables',items:['<strong>Change:</strong> sucrose concentration.','<strong>Measure:</strong> percentage change in potato mass after a fixed time.','<strong>Keep consistent:</strong> potato source, cylinder dimensions, time, solution volume and temperature.'],task:'Choose two controls. Explain why changing either could affect your conclusion.'}),
      p('practical-measure','Thinking','content','What would improve the measurements?','method',{nav:'Think about measurement',items:['Gently blot surface liquid off consistently before each weighing. The balance also measures liquid left on the surface.','Use repeats at each concentration to assess variation and calculate a mean.','Use the department’s practical method in Week 4. Today, explain the science behind the method.'],task:'Why would equal mass gains be misleading if two cylinders started at different masses?'}),
      p('exit','Assess','content','Explain the result','tissue',{nav:'Exit check',text:'A potato cylinder loses mass in a concentrated sucrose solution.',items:['Explain the loss using <strong>water</strong>, <strong>net movement</strong>, the concentrations and the <strong>cell membrane</strong>.','Give one control that would make comparisons between solutions more useful.'],task:'Return to your first prediction. Correct it if your explanation has changed.',support:{...support.tissue,start:[support.osmosis.start[1],support.method.start[1]],understand:[support.tissue.understand[0],support.method.understand[1]],hot:support.method.hot}})
    ]
  };
})();
